### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by robbinonline** [sakirtemel/MMM-alexa#6]
I got this error with installation:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN MMM-alexa@0.0.4 No repository field.
```

And the next when i launch MagicMirror
 
```
Whoops! There was an uncaught exception...
Error: Module version mismatch. Expected 50, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/home/pi/MagicMirror/modules/MMM-alexa/node_modules/bindings/bindings.js:76:44)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?

```

Red button shows up, button pressing the fysic button nothing..

**Comment by sakirtemel** [comment]
@robbinonline yeah it's a nightmare, I'm going to write a complete documentation for that.

What I was doing is, using electron rebuild, adding the module inside package.json as dependencies(MagicMirror's root). Removing the node_modules inside `MMM-alexa`, and also having the module cloned under modules.
